#!/bin/sh

### BEGIN INIT INFO
# Provides:        hsen
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start Hosts3D Sensor
### END INIT INFO

PATH=/bin:/sbin:/usr/bin:/usr/sbin

. /lib/lsb/init-functions

NAME=hsen
DESC="Hosts3D Sensor"
AGENT=/usr/local/bin/hsen

test -x $AGENT || exit 5

if [ -r /etc/default/$NAME ]; then
	. /etc/default/$NAME
fi

case $1 in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
  		start-stop-daemon --start --quiet --exec $AGENT -- $SENID $IFACE $DESTN $PROMS -d
		log_end_msg $?
  		;;
	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
  		start-stop-daemon --stop --quiet --exec $AGENT
		log_end_msg $?
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			exit 0
		else
			$0 restart
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status=`ps -ef | grep $AGENT | grep -v grep | wc -l`
		if [ $status -eq 0 ]; then
			log_failure_msg "$DESC is not running."
		else
			log_success_msg "$DESC is running."
		fi
		exit $status
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
